package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/takanoriyanagitani/go-addrs2ql/graph/model"
	ni "github.com/takanoriyanagitani/go-addrs2ql/netif"
)

// Addrs is the resolver for the addrs field.
func (r *netInterfaceResolver) Addrs(ctx context.Context, obj *model.NetInterface) ([]*model.Addr, error) {
	var ix string = obj.Index
	return ni.AddrsByIfaceIndex(ix)
}

// NetInterface is the resolver for the netInterface field.
func (r *queryResolver) NetInterface(ctx context.Context, name string) (*model.NetInterface, error) {
	iface, e := ni.IfaceByName(name)
	if nil != e {
		return nil, e
	}

	var converted model.NetInterface = ni.IfaceToModel(*iface)

	return &converted, nil
}

// NetInterfaceByIndex is the resolver for the netInterfaceByIndex field.
func (r *queryResolver) NetInterfaceByIndex(ctx context.Context, id string) (*model.NetInterface, error) {
	iface, e := ni.IfaceByIndex(id)
	if nil != e {
		return nil, e
	}

	var converted model.NetInterface = ni.IfaceToModel(*iface)

	return &converted, nil
}

// NetIfaces is the resolver for the netIfaces field.
func (r *queryResolver) NetIfaces(ctx context.Context, pattern *string) ([]*model.NetInterface, error) {
	var pat string
	if nil != pattern {
		pat = *pattern
	}

	ifaces, e := ni.IfacesByPattern(pat)
	if nil != e {
		return nil, e
	}

	ret := make([]*model.NetInterface, 0, len(ifaces))

	for _, iface := range ifaces {
		var converted model.NetInterface = ni.IfaceToModel(iface)
		ret = append(ret, &converted)
	}

	return ret, nil
}

// AddrsByIfaceIndex is the resolver for the addrsByIfaceIndex field.
func (r *queryResolver) AddrsByIfaceIndex(ctx context.Context, ifid string) ([]*model.Addr, error) {
	return ni.AddrsByIfaceIndex(ifid)
}

// NetInterface returns NetInterfaceResolver implementation.
func (r *Resolver) NetInterface() NetInterfaceResolver { return &netInterfaceResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type netInterfaceResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
