// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Addr struct {
	Network string `json:"network"`
	String  string `json:"string"`
}

type NetInterface struct {
	Index        string  `json:"index"`
	Mtu          int32   `json:"mtu"`
	Name         string  `json:"name"`
	HardwareAddr string  `json:"hardwareAddr"`
	Addrs        []*Addr `json:"addrs,omitempty"`
}

type Query struct {
}
